In [88]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [89]:
df = pd.read_csv('data/football.csv')
df.head()

Day  Month  Year          Type   Own_Team   Opp_Team  Own_Goal  Opp_Goal
0    7      7  2021          EURO    England    Denmark         2         1
1    7      7  2021          EURO    Denmark    England         1         2
2    7      7  2021  Copa America  Argentina   Colombia         1         1
3    7      7  2021  Copa America   Colombia  Argentina         1         1
4    6      7  2021          EURO      Italy      Spain         1         1

## Convert string value to numaric value

In [90]:
types = list(df['Type'].unique())
# types
# types.index('Copa America')
typeDict = {}
for tV in types:
    typeDict[tV]=types.index(tV)
# typeDict
# typeDict['EURO']
typeN = []
for i in df['Type']:
    typeN.append(typeDict[i])
df['Type']=typeN
teams = list(df['Own_Team'].unique())
teamDict ={}
for teamV in teams:
    teamDict[teamV]=teams.index(teamV)
ownTeamN = []
oppTeamN = []
for j in df['Own_Team']:
    ownTeamN.append(teamDict[j])
for k in df['Opp_Team']:
    oppTeamN.append(teamDict[k])
df['Own_Team']= ownTeamN
df['Opp_Team']= oppTeamN

In [91]:
len(df)

798

# Training & Testing Values

In [92]:
x = df.iloc[:,:-2]
x

Day  Month  Year  Type  Own_Team  Opp_Team
0      7      7  2021     0         0         1
1      7      7  2021     0         1         0
2      7      7  2021     1         2         3
3      7      7  2021     1         3         2
4      6      7  2021     0         4         5
..   ...    ...   ...   ...       ...       ...
793   20      6  2008     0        33        19
794   13      6  2008     0         4        53
795   13      6  2008     0        21        20
796   13      6  2008     0        53         4
797   13      6  2008     0        20        21

[798 rows x 6 columns]

In [93]:
y = np.array(df.iloc[:,-2])
y[5:10]

array([1, 1, 0, 3, 0], dtype=int64)

In [94]:
trainX,testX,trainY,testY = train_test_split(x,y,test_size=0.33,random_state=25)

## Classification

### Gauuian Naive Bayes

In [95]:
trainX.shape

(534, 6)

In [96]:
trainY.shape

(534,)

In [97]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(trainX,trainY)
gnb.predict(x[5:7])

array([1, 1], dtype=int64)

### Support Vector Machine (linear)

In [98]:
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(trainX,trainY.ravel())
svm.predict(x[5:7])

array([1, 1], dtype=int64)

### Decision Tree Classifier

In [99]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=0)
dtc.fit(trainX,trainY.ravel())
dtc.predict(x[5:7])

array([1, 7], dtype=int64)

In [100]:
from sklearn.linear_model import LogisticRegression
lor = LogisticRegression(random_state=40).fit(trainX,trainY.ravel())
lor.predict(x[5:7])

C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 1], dtype=int64)

In [101]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=2, random_state=0)
rfc.fit(trainX,trainY.ravel())
rfc.predict(x[5:7])

array([1, 1], dtype=int64)

In [102]:
from sklearn.linear_model import LinearRegression
lir = LinearRegression().fit(trainX,trainY.ravel())
lir.predict(x[5:7])

array([1.15216112, 1.18606742])

In [106]:
print('Linear Regression\t:',lir.score(testX,testY)*100)
print('Support Vector Machine\t:',svm.score(testX,testY)*100)
print('Decision Tree\t\t:',dtc.score(testX,testY)*100)
print('Naive Bayes\t\t:',gnb.score(testX,testY)*100)
print('Logistic Regression\t:',lor.score(testX,testY)*100)
print('Random Forest\t\t:',rfc.score(testX,testY)*100)

Linear Regression		: 1.796819181408249
Support Vector Machine	: 40.15151515151515
Decision Tree		: 31.439393939393938
Naive Bayes		: 39.77272727272727
Logistic Regression	: 37.878787878787875
Random Forest		: 38.63636363636363
